### ISSUE TITLE
Problem running from source

### ISSUE THREAD

**Issue by jakkemerke** [hexoshi/hexoshi#1]
I like the game. I was thinking about making a few changes so I tried the source. I run these steps and get the following error when I run in an isolated env in a venv:  

```
git clone https://github.com/hexoshi/hexoshi.git hexoshi_clone && cd hexoshi_clone
python3 -m venv venv
source venv/bin/activate
pip3 install --upgrade pip
pip3 install -r requirements.txt 
./hexoshi.py -h
cd data/locale && ./build.py && cd ../..
./hexoshi.py -mq || deactivate && echo "it failed, now leaving venv"

```

> pygame 2.0.0 (SDL 2.0.12, python 3.7.3)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Initializing game system...
> Initializing GUI system...
> Loading resources...
> Fatal Python error: (pygame parachute) Segmentation Fault
> 
> Current thread 0x00007fcf63e0b740 (most recent call first):
>   File "/home/foobar/hexoshi_clone/venv/lib/python3.7/site-packages/sge/gfx.py", line 2871 in __init__
>   File "/home/foobar/hexoshi_clone/venv/lib/python3.7/site-packages/sge/gfx.py", line 2971 in __init__
>   File "/home/foobar/hexoshi_clone/venv/lib/python3.7/site-packages/sge/gfx.py", line 2833 in from_sprite
>   File "./hexoshi.py", line 6954 in <module>
> Aborted
> it failed, now leaving venv

**Comment by jakkemerke** [comment]
To fix it, change the requirements.txt for pygame to something like:

pygame<2.0.0

**Comment by jakkemerke** [comment]
I pushed my changes. And I changed a few other things just for my own ease of use.  

https://github.com/jakkemerke/hexoshi/commit/25ee53d2bd5373a61c30fdf0a7754b9bd38d57f1

**Comment by onpon4** [comment]
Thanks for letting us know of the incompatibility. I'll probably actually want to update SGE to support the Pygame 2 API; I have no plans to keep this stuck at SDL 1.2.

🕵️

**Comment by onpon4** [comment]
https://github.com/python-sge/sge/commit/b4966d06d9b6afdb88fd57f28aac67e95809c82c has a typo in its commit message (meant to write "Pygame 2", not "Python 2"), but it should fix this problem. I'll close this issue once a new SGE release is made.

🕵️

**Comment by onpon4** [comment]
Just pushed out the 1.7.1 release of the SGE into PyPI, so this should be fixed now.

🕵️
